"""implementacion chatbot

Revision ID: 25cbf599f61e
Revises: e4814615378f
Create Date: 2025-11-03 02:49:18.864495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25cbf599f61e'
down_revision = 'e4814615378f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pqrd', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_chatbot_activo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('mensajes_chatbot', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_escalado', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pqrd', schema=None) as batch_op:
        batch_op.drop_column('fecha_escalado')
        batch_op.drop_column('mensajes_chatbot')
        batch_op.drop_column('es_chatbot_activo')

    # ### end Alembic commands ###
