"""Add fecha_reactivacion_auto to Pqrd

Revision ID: 562bca3e022e
Revises: 25cbf599f61e
Create Date: 2025-11-07 15:57:47.253814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562bca3e022e'
down_revision = '25cbf599f61e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pqrd', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_reactivacion_auto', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pqrd', schema=None) as batch_op:
        batch_op.drop_column('fecha_reactivacion_auto')

    # ### end Alembic commands ###
