"""automatico chatbot

Revision ID: 8e8612f9e170
Revises: aaf781af1133
Create Date: 2025-11-07 16:49:30.035378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8612f9e170'
down_revision = 'aaf781af1133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pqrd', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_reactivacion_auto', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pqrd', schema=None) as batch_op:
        batch_op.drop_column('fecha_reactivacion_auto')

    # ### end Alembic commands ###
