"""prueba fecha error

Revision ID: aaf781af1133
Revises: 562bca3e022e
Create Date: 2025-11-07 16:36:16.807654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf781af1133'
down_revision = '562bca3e022e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pqrd', schema=None) as batch_op:
        batch_op.drop_column('fecha_reactivacion_auto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pqrd', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_reactivacion_auto', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
