"""pqrd, chat

Revision ID: c78f2bfe3052
Revises: 
Create Date: 2025-11-03 00:42:43.972202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78f2bfe3052'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('pqrd', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultima_respuesta', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('esperando_respuesta_de', sa.String(length=20), nullable=True))
        batch_op.alter_column('id_pqrd',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.drop_index('idx_pqrd_estado')
        batch_op.drop_index('idx_pqrd_fecha_creacion')
        batch_op.drop_index('idx_pqrd_id_agente')
        batch_op.drop_index('idx_pqrd_id_cliente')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pqrd', schema=None) as batch_op:
        batch_op.create_index('idx_pqrd_id_cliente', ['id_cliente'], unique=False)
        batch_op.create_index('idx_pqrd_id_agente', ['id_agente'], unique=False)
        batch_op.create_index('idx_pqrd_fecha_creacion', ['fecha_creacion'], unique=False)
        batch_op.create_index('idx_pqrd_estado', ['estado'], unique=False)
        batch_op.alter_column('id_pqrd',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('esperando_respuesta_de')
        batch_op.drop_column('ultima_respuesta')

    with op.batch_alter_table('contactos', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
