"""corregiendo chat

Revision ID: e4814615378f
Revises: c78f2bfe3052
Create Date: 2025-11-03 02:15:31.845893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4814615378f'
down_revision = 'c78f2bfe3052'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pqrd_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_automatico', sa.Boolean(), nullable=True))
        batch_op.drop_column('es_automático')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pqrd_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('es_automático', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('es_automatico')

    # ### end Alembic commands ###
